### ISSUE TITLE
Other entities become invisible while self is invisible

### ISSUE THREAD

**Issue by mbax** [KittehOrg/Vanish#1]
Upstream bug. See https://github.com/SpongePowered/SpongeCommon/issues/391

**Comment by wizdude** [comment]
i read the notes above - interesting to note in the current sponge and your plugin that the other players that become invisible do become visible after they have moved around for a little bit.

but from the looks of things this is more of an issue with sponge itself. hopefully it will get resolved :smile:

**Comment by mbax** [comment]
It was resolved two days ago, I just forgot to close this since I haven't had the chance in those two days to continue work on the plugin ^_^

**Comment by wizdude** [comment]
i assume you mean that you've resolved this in a new build which hasn't been published yet or that it's being resolved upstream in a new sponge build? 

i'm using sponge 1018 and your plugin 4.0.0 and the issue exists as of right now.

**Comment by mbax** [comment]
Oh dear. I'll go investigate.

**Comment by mbax** [comment]
@wizdude As it turns out, the "latest download" link on Sponge's download site doesn't currently list the actual latest build. Click the "Show all downloads" button in the mean time to get the latest build, until it gets fixed.
